# fishros deploy tool 所有的操作都在工程目录进行
name: nav2cn
tag: master
pipline:
  - install-dep
  - build
  - install
stages:
  install-dep:
    - npm run install-dep
  build:
    - npm run build
  install:
    - rm -rf /root/nav2/dev/nav2cn/*
    - cp -r docs/.vuepress/dist/* /root/nav2/dev/nav2cn/
    - rm -rf /root/nav2/master/nav2cn/*
    - cp -r docs/.vuepress/dist/* /root/nav2/master/nav2cn/
